<a href="https://colab.research.google.com/github/TanmayLimje/Machine-Learning/blob/main/ML_lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("/Heart.csv")

In [6]:
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [8]:
df.shape

(303, 15)

In [10]:
df.isnull

<bound method DataFrame.isnull of      Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150
1             2   67    1  asymptomatic     160   286    0        2    108
2             3   67    1  asymptomatic     120   229    0        2    129
3             4   37    1    nonanginal     130   250    0        0    187
4             5   41    0    nontypical     130   204    0        2    172
..          ...  ...  ...           ...     ...   ...  ...      ...    ...
298         299   45    1       typical     110   264    0        0    132
299         300   68    1  asymptomatic     144   193    1        0    141
300         301   57    1  asymptomatic     130   131    0        0    115
301         302   57    0    nontypical     130   236    0        2    174
302         303   38    1    nonanginal     138   175    0        0    173

     ExAng  Oldpeak  Slope   Ca        Thal  AHD
0        0      2.3      3  0.0       fixed   No
1        1      1.5      2  3.0      normal  Yes
2        1      2.6      2  2.0  reversable  Yes
3        0      3.5      3  0.0      normal   No
4        0      1.4      1  0.0      normal   No
..     ...      ...    ...  ...         ...  ...
298      0      1.2      2  0.0  reversable  Yes
299      0      3.4      2  2.0  reversable  Yes
300      1      1.2      2  1.0  reversable  Yes
301      0      0.0      2  1.0      normal  Yes
302      0      0.0      1  NaN      normal   No

[303 rows x 15 columns]>

In [11]:
df.describe()

,Unnamed: 0,Age,Sex,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,299.000000
mean,152.000000,54.438944,0.679868,131.689769,246.693069,0.148515,0.990099,149.607261,0.326733,1.039604,1.600660,0.672241
std,87.612784,9.038662,0.467299,17.599748,51.776918,0.356198,0.994971,22.875003,0.469794,1.161075,0.616226,0.937438
min,1.000000,29.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000
25%,76.500000,48.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000
50%,152.000000,56.000000,1.000000,130.000000,241.000000,0.000000,1.000000,153.000000,0.000000,0.800000,2.000000,0.000000
75%,227.500000,61.000000,1.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,1.000000
max,303.000000,77.000000,1.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,3.000000

df.dtypes

In [12]:
df.dtypes

Unnamed: 0      int64
Age             int64
Sex             int64
ChestPain      object
RestBP          int64
Chol            int64
Fbs             int64
RestECG         int64
MaxHR           int64
ExAng           int64
Oldpeak       float64
Slope           int64
Ca            float64
Thal           object
AHD            object
dtype: object

In [15]:
df.mean().Age

<ipython-input-15-624ce96b35bf>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean().Age

54.43894389438944

import math
from sklearn.model_selection import train_test_split

In [17]:
import math

In [19]:
from sklearn.model_selection import train_test_split

In [22]:
list1 = ["Age", "Sex", "ChestPain", "RestBP", "Chol"]
A = df[list1]
B = df["Thal"]

In [23]:
A_train, A_test, B_train, B_test = train_test_split(A, B, random_state = 0, test_size = 0.75, train_size = 0.25)

In [24]:
A_train

     Age  Sex     ChestPain  RestBP  Chol
84    52    1    nontypical     120   325
170   70    1    nonanginal     160   269
121   63    0  asymptomatic     150   407
140   59    1    nontypical     140   221
258   70    1    nontypical     156   245
..   ...  ...           ...     ...   ...
251   58    1  asymptomatic     146   218
192   43    1  asymptomatic     132   247
117   35    0  asymptomatic     138   183
47    50    1  asymptomatic     150   243
172   59    0  asymptomatic     174   249

[75 rows x 5 columns]

In [25]:
B_train

84         normal
170    reversable
121    reversable
140        normal
258        normal
          ...
251    reversable
192    reversable
117        normal
47     reversable
172        normal
Name: Thal, Length: 75, dtype: object

In [26]:
(df == 0).sum()

Unnamed: 0      0
Age             0
Sex            97
ChestPain       0
RestBP          0
Chol            0
Fbs           258
RestECG       151
MaxHR           0
ExAng         204
Oldpeak        99
Slope           0
Ca            176
Thal            0
AHD             0
dtype: int64